name: Onliquidity Todo 

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Cache node_modules
        uses: actions/cache@main
        id: cache-node
        env:
          cache-name: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        # Always run this, so it throws if the package and lockfile don't match
        run: yarn install --non-interactive --frozen-lockfile

  unit-test:
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Restore dependencies
        uses: actions/cache@main
        env:
          cache-name: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn test
